### ISSUE TITLE
Community Survey materials

### ISSUE THREAD

**Issue by split-infinity** [popcorndao/Marketing-Ad-hoc#17]
Description: 
We need visual assets for announcing the Community Survey

It will be shared on Discord and Twitter

Copy:
v1:
Help build Popcorn!
Take the Community Survey

v2:
Popcorn Community Survey
Your DAO. Your Popcorn.

v3:
Help shape the future of Popcorn.
Check out the Popcorn Community Survey!
Your feedback counts.

**Comment by split-infinity** [comment]
requested POPstar assistance here https://discord.com/channels/810280562626658334/916403464928649296/949079486551441430

**Comment by mishraashish006** [comment]
![community survey1.jpg](https://images.zenhubusercontent.com/618a6a84d0bd0e20ee3cf8bb/25b0b3b7-be5d-4c5c-90b7-11db093d9308)![community survey2.jpg](https://images.zenhubusercontent.com/618a6a84d0bd0e20ee3cf8bb/0a0d2395-cf2d-4f35-a562-e1c140c9525b)![community survey3.jpg](https://images.zenhubusercontent.com/618a6a84d0bd0e20ee3cf8bb/f8ba4f15-0e28-4ec5-a656-0978b91c4c75)

**Comment by FanFanDAO** [comment]
@split-infinity @anthonymartin I like option 2 & 3.
