### ISSUE TITLE
Community Call Graphic Refresh

### ISSUE THREAD

**Issue by split-infinity** [popcorndao/Marketing-Ad-hoc#19]
Hello again! Our community calls occur every 2 weeks and feature various guest speakers. Previous community call graphics included:

![comm call feb 16.jpg](https://images.zenhubusercontent.com/6186cf52b420f550fa373327/9d94ef79-d582-40fc-815f-47c67311a75b)

Rather than use the same graphic every 2 weeks, we'd like to have 3-4 that we can use on rotation. 

For this month we need graphics for March 16 and March 30. They can be a different color and design to the above reference but still on brand for Popcorn. 

The speakers for these dates have not been selected yet, so we can forego that element and keep the copy matching the above reference. 

Ideally we can have 3-4 editable graphics templates that the marketing team can easily update every 2 weeks to feature the new date and (optionally) the names of the guest speakers.

Thank you!

**Comment by FanFanDAO** [comment]
Is this a new request? Can create a new ticket for new request?

**Comment by split-infinity** [comment]
@FanFanDAO this is a new ticket for a new request. The dates do not match those specified however

**Comment by FanFanDAO** [comment]
@split-infinity they look good to me.

**Comment by split-infinity** [comment]
The dates are wrong?

**Comment by FanFanDAO** [comment]
![community call 1.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/9b9c5992-49b4-4c8b-a3a5-e98ec0d0da2c)![community call 4.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/1b2d1beb-b3f1-47b8-9ae6-fe8cb0beea11)![community call 3.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/ce292dab-4d25-45d5-9a1e-3da17e74af8d)![community call 5.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/3f2dddd4-cc0e-4fd6-9ec9-708f6c2ec0ca)
