### ISSUE TITLE
Change to previous graphic needed urgently please

### ISSUE THREAD

**Issue by MrsBadgerface** [popcorndao/Marketing-Ad-hoc#20]
**Scope:** Due to being diagnosed with Covid, the second of the planned Discord design sessions was cancelled and I have just been told he is well enough to do the session tomorrow. This means that we need new graphics urgently, so we can inform the community and our Twitter followers.

**Changes needed:** Please can you take the third session graphic and rename it to the second session, keeping all other information the same. Thanks!

![Discord-identity-session-3.png](https://images.zenhubusercontent.com/6080275bb891652bba91375c/86a003fb-5ce2-404e-bb85-c5e73b7afb55)

**Please note:** We will have the third session at some point in the future, and when I know when it will be, I'll make another ticket.

**Comment by FanFanDAO** [comment]
Updated:
![community call-3.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/c0e38a77-a816-4dfb-874b-c9424023c10b)
