### ISSUE TITLE
Change of date needed asap please

### ISSUE THREAD

**Issue by MrsBadgerface** [popcorndao/Marketing-Ad-hoc#21]
**Scope:** Due to illhealth with Covid, the dates for the third Discord Design session has changed and the graphic needs updating asap please so we can market it asap.

**Details:** Please change current date to: Friday 18th March. Time of call and all other details stay the same. 

**Timeframe:** By Tuesday 15th, 8pm UK time.

Thank you.

![Discord-identity-session-3.png](https://images.zenhubusercontent.com/6080275bb891652bba91375c/a4816d3b-89ed-4a75-9dd5-37aa345ba6a9)

**Comment by FanFanDAO** [comment]
Updated design 
![community call-3.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/2754a27d-d9e5-469f-83d5-24fa68e703a4)
