### ISSUE TITLE
(Priority 2) BAYC Beneficiary Marketing

### ISSUE THREAD

**Issue by split-infinity** [popcorndao/Marketing-Ad-hoc#23]
Description: We need marketing materials to promote the Popcorn x Bored Ape Yacht Club airdrop which raised POP for charities. 

**_(logos can be substituted for copy)_ Copy: ** 

Bored Ape Yacht Club x Popcorn Charitable POPdrop

So far, apes have allocated:

UNICEF Crypto Fund: 5,500 POP
Pathway to Education: 4,640 POP
Panthera: 4,400 POP
Rhino Ark Foundation: 3,200 POP
Rock Your Life: 1,860 POP

Only at https://bayc.popdrop.me/

**Resources:**
https://boredapeyachtclub.com/
https://www.panthera.org/
https://www.unicef.org/innovation/stories/unicef-cryptofund
https://rhinoark.org/
https://www.pathwaystoeducation.ca/
https://rockyourlife.de/

**Dimensions**
Standard banner size for Twitter

**Comment by split-infinity** [comment]
It was decided to keep the pop amounts off of the tweeted image so we're going to go with an existing image

**Comment by mishraashish006** [comment]
@split-infinity current status of this ticket please?
Do we keep the amounts in design ? Got a message saying we need not.

**Comment by split-infinity** [comment]
@mishraashish006 Sorry, my reply to the email thread didn't get posted here. There was some confusion over whether to include the numbers but we decided to include them so I deleted the comments. We can move forward with the ticket as written. Thank you!

**Comment by mishraashish006** [comment]
![popcorn x bayc.jpg](https://images.zenhubusercontent.com/618a6a84d0bd0e20ee3cf8bb/e142a1d7-3c59-40c4-867b-15044aeb25bf)

**Comment by split-infinity** [comment]
Hi @mishraashish006 - Can we also try a more basic version where the copy is only:

"Popcorn and Bored Apes Making an Impact"

With just the popcorn logo and the ape?

we'll put the beneficiaries in the tweet text rather in the image.

Thanks!

**Comment by mishraashish006** [comment]
![popcorn x bayc.jpg](https://images.zenhubusercontent.com/618a6a84d0bd0e20ee3cf8bb/770c8c62-4ca4-4074-9c82-58a35be796b3)

something like this ?
