### ISSUE TITLE
(Priority 1) Popcorn supports #AfricansInUkraine

### ISSUE THREAD

**Issue by split-infinity** [popcorndao/Marketing-Ad-hoc#24]
**Description:** 

We want to show our support for the #AfricansInUkraine movement. 

The tone can be a bit more serious so we can avoid the use of pop cats. 

These graphics will accompany this tweet:

![image.png](https://images.zenhubusercontent.com/6186cf52b420f550fa373327/37408023-67dc-4a03-9f57-80e2eaa50907)

**Copy:**

Popcorn proudly supports #AfricansInUkraine

**Dimensions:**

Standard tweet banner

**Comment by mishraashish006** [comment]
![#africansinukraine.jpg](https://images.zenhubusercontent.com/618a6a84d0bd0e20ee3cf8bb/d86eb782-e895-4e55-ad12-e0fc33e13f9f)

**Comment by split-infinity** [comment]
great! Can we incorporate the following logos as well? 

![image.png](https://images.zenhubusercontent.com/6186cf52b420f550fa373327/e89d80a7-ad94-4e1f-a567-ff8e8fc7fa3b)

![image (1).png](https://images.zenhubusercontent.com/6186cf52b420f550fa373327/94064ce9-efd6-433c-8ca3-1a5f8dddcaf2)

![ukrainedao.jpg](https://images.zenhubusercontent.com/6186cf52b420f550fa373327/15bf13a9-1714-4414-80a2-52e9c070e59a)

![image.png](https://images.zenhubusercontent.com/6186cf52b420f550fa373327/3f5e5ed2-4f2d-4358-880c-b7ba947ba66a)

**Comment by mishraashish006** [comment]
![#africansinukraine.jpg](https://images.zenhubusercontent.com/618a6a84d0bd0e20ee3cf8bb/97d4508e-280f-45c4-a99f-e9228b844a12)

**Comment by FanFanDAO** [comment]
@mishraashish006 Hey Ashish, when you finish the task and move the ticket to the review column, make sure that you assign the responsible person, usually the person who created the ticket and unassign yourself. xox
