### ISSUE TITLE
Intergalactic Community Call 3-30 

### ISSUE THREAD

**Issue by split-infinity** [popcorndao/Marketing-Ad-hoc#25]
Our next community call features our very own Axel aka INTERGALACTIC

Therefore we're looking for a version of the community call graphics that features stars and a spaceship

Copy:

Community Call featuring Special Guest Mr. Intergalactic

Wednesday, March 30

![image.png](https://images.zenhubusercontent.com/6186cf52b420f550fa373327/9ec4c433-1374-4d2f-8668-09245a946ed2)

**Comment by split-infinity** [comment]
One fix to the pasted time copy - 'UCT' should be 'UTC'

**Comment by mishraashish006** [comment]
![community call 7.jpg](https://images.zenhubusercontent.com/618a6a84d0bd0e20ee3cf8bb/f1cc9830-cb21-461a-8276-01f6a6fca37b)
