### ISSUE TITLE
Butter Promotion

### ISSUE THREAD

**Issue by split-infinity** [popcorndao/Marketing-Ad-hoc#26]
We're looking for two sets of graphics to 1) hype the release of Butter and 2) announce the release.

Copy:

1)

v1: Butter is coming...

v2: 🧈 soon

2)

v1: Butter Has Arrived!
Mint. Stake. Make an Impact.
popcorndao.finance

v2: Butter Has Landed!
popcorndao.finance

v3: Butter is Here!
popcorndao.finance

**Comment by mishraashish006** [comment]
![butter soon.jpg](https://images.zenhubusercontent.com/618a6a84d0bd0e20ee3cf8bb/0c324af1-62f5-4200-8839-09548679c1b2)![butter soon 2.jpg](https://images.zenhubusercontent.com/618a6a84d0bd0e20ee3cf8bb/391f3793-a2e1-4a3c-aa9b-5451fb37933d)

**Comment by mishraashish006** [comment]
![butter arrived.jpg](https://images.zenhubusercontent.com/618a6a84d0bd0e20ee3cf8bb/f03af249-db3d-4654-a5db-2ed059cb597e)![butter arrived-1.jpg](https://images.zenhubusercontent.com/618a6a84d0bd0e20ee3cf8bb/5f961dc0-6352-4cf7-8b94-760eabbd73a8)![butter arrived-2.jpg](https://images.zenhubusercontent.com/618a6a84d0bd0e20ee3cf8bb/544beb4f-84a5-4cef-994c-97d02a30102c)
