### ISSUE TITLE
Butter Banner

### ISSUE THREAD

**Issue by sirkisselgof** [popcorndao/Marketing-Ad-hoc#27]
I need to put the latest Butter design from Olga into a branded banner.

It should have the following:

- The Visual
- Our logo and wordmark
- "DeFi tastes better with Butter!"

![Butter FINAL.png](https://images.zenhubusercontent.com/61530817321ea2a20d443b97/856aedd9-f8e7-4fdd-849e-8cbb35100c9b)

**Comment by annisharafi** [comment]
Update for banner
1. facebook banner
![Facebook Cover.png](https://images.zenhubusercontent.com/6138be30f402af74c178f38b/18ac848e-b715-4c48-80cb-aa46b390c42d)

2. twitter banner
![Twitter Cover.png](https://images.zenhubusercontent.com/6138be30f402af74c178f38b/4b358212-0338-44c3-bf0d-5f5609317a19)

3. Linkedin Banner
![LinkedIn Cover.png](https://images.zenhubusercontent.com/6138be30f402af74c178f38b/3f6bab64-feba-45c5-94dd-c10c58a1f545)

4. Youtube Banner
![yt banner.png](https://images.zenhubusercontent.com/6138be30f402af74c178f38b/67ff4f3c-187a-40e9-b955-c5aa3bbbdc8a)

**Comment by annisharafi** [comment]
1. Square
![Square.png](https://images.zenhubusercontent.com/6138be30f402af74c178f38b/79c3ec0c-ccec-46b8-9185-1ab1ee87de63)

2. Twitter Banner
![Twitter Cover.png](https://images.zenhubusercontent.com/6138be30f402af74c178f38b/14b98748-3907-4f15-af47-627b5915f729)
