### ISSUE TITLE
Medium article graphics

### ISSUE THREAD

**Issue by split-infinity** [popcorndao/Marketing-Ad-hoc#29]
Header image for Medium article "Popcorn: Impact Made Easy"

No copy

Just the Butter logo (below) on the left with a planet earth on the right. Each circle equal dimensions

![butter icon 3.png](https://images.zenhubusercontent.com/6186cf52b420f550fa373327/c9458eab-92ff-4140-b618-95bcabe3f481)

Thank you!

**Comment by annisharafi** [comment]
version 01
<img width="1500" alt="version 01" src="https://user-images.githubusercontent.com/22950097/162761449-df99c8fc-ab44-4c3c-a868-bf41a06dfa7a.png">


version 02
<img width="1500" alt="version 02" src="https://user-images.githubusercontent.com/22950097/162761360-8e025e4d-e76c-4fb4-bf4e-7c4a01fd1328.png">
