### ISSUE TITLE
Twitter Spaces graphics

### ISSUE THREAD

**Issue by split-infinity** [popcorndao/Marketing-Ad-hoc#30]
We're looking to promote our Twitter Spaces, happening instead of our discord community calls going forward. 

Dimensions: image for sharing on Twitter

we can also include the new butter logo: ![butter icon 3.png](https://images.zenhubusercontent.com/6186cf52b420f550fa373327/86166f0e-43f9-4cbe-a959-754cb255935a)

Copy:

Popcorn Twitter Space
Wednesday, April 13
4:30pm UTC / 12:30pm EDT

---

Here is our old community call graphics for reference:

![community call march 16th.png](https://images.zenhubusercontent.com/6186cf52b420f550fa373327/74d5632e-d0ee-4bfa-ba70-ee15257fc688)

thank you!

**Comment by annisharafi** [comment]
@split-infinity here update for community sharing

![community call 8](https://user-images.githubusercontent.com/22950097/162762652-ed6cef46-a587-4348-95e9-cfe14488fb57.jpg)

**Comment by split-infinity** [comment]
Thank you @annisharafi , can we try another version where:

Instead of 'Community call' it says: 

"Let's Talk Butter"

and then beneath that it says 

"Popcorn Twitter Spaces 
Every Wednesday at 4:30pm UTC / 12:30pm EDT
@Popcorn_DAO"

We can get rid of the current 'popcorn twitter spaces' bubble with the twitter icon. Instead, we can put the twitter blue bird icon after '@Popcorn_DAO'

**Comment by annisharafi** [comment]
got it @split-infinity 
![community call 8](https://user-images.githubusercontent.com/22950097/162789227-e776183c-fa3d-4848-a0a9-e1787faad34c.jpg)

**Comment by split-infinity** [comment]
perfect thank you @annisharafi !
