### ISSUE TITLE
Beneficiary Twitter Space with Elmui.ai and Carbon Collectible Nfts Banner

### ISSUE THREAD

**Issue by Joris000** [popcorndao/Marketing-Ad-hoc#31]
We need a banner to promote our first beneficiary twitter spaces with [Carbon Collectible Nfts](https://carboncollectiblenfts.com/) and [Elimu.ai](https://eng.elimu.ai/)

Elimu.ai: https://twitter.com/elimu_ai

![image](https://user-images.githubusercontent.com/106169378/170087576-1c48f9cb-9ef1-48e4-8c93-53059e32c8f5.png)

Carbon Collectible NFTs: https://twitter.com/CarbonOffsetNFT

![CCNFT logo](https://user-images.githubusercontent.com/106169378/170087874-98d1f65e-9143-4ee9-a323-47c47021ca99.jpeg)

**Comment by FanFanDAO** [comment]
@Joris000 Hey Joris, may I know when you need this by?
It would be good if you can go with the below format:
## Description
## Specific Acceptance Criteria
## Resources
File links
## General Requirements
## Image References

**Comment by Joris000** [comment]
Hey @FanFanDAO 

Thank you for clarifying. I think as soon as possible would be good so that we can start the promotion. 

**Description**
We need a banner with the logos of Popcorn, [Carbon Collectible Nfts](https://carboncollectiblenfts.com/) and [Elimu.ai](https://eng.elimu.ai/) to promote our first beneficiary spaces on twitter next Tuesday. 
**Specific Acceptance Criteria**
None 
**Resources**
File links
https://user-images.githubusercontent.com/106169378/170087874-98d1f65e-9143-4ee9-a323-47c47021ca99.jpeg
https://user-images.githubusercontent.com/106169378/170087576-1c48f9cb-9ef1-48e4-8c93-53059e32c8f5.png
**General Requirements**
No specific requirements 
**Image References**
Mail attachments

**Comment by annisharafi** [comment]
@Joris000 Hi,
Can you help me to fill this :
- banner title :
- date & time :
- speaker (*if there is) :

**Comment by Joris000** [comment]
Sure, sorry that I did not include that info earlier: 

banner title : Popcorn Foundation Beneficiary Twitter Spaces Vol 1
date & time : May 31th, 7pm CET
speaker (*if there is) : Harsh Acharya from Elimu.ai and Mark Lawrence from Carbon Collectible NFTs

**Comment by annisharafi** [comment]
do you have additional information about the job title of the speaker?

**Comment by Joris000** [comment]
I just asked, will give an update as soon as I have an answer :)

**Comment by Joris000** [comment]
speaker (*if there is) : 
Harsh Acharya: APJ and NA Leader of Elimu.ai
Mark Lawrence: Co-Founder of Carbon Collectible NFTs

These are the speakers with roles

**Comment by annisharafi** [comment]
@Joris000 @FanFanDAO updated
![Popcorn Foundation Beneficiary Twitter Spaces Vol 1.jpg](https://images.zenhubusercontent.com/6138be30f402af74c178f38b/9d4c9e3a-2d1d-427a-9627-d2a06886fd59)

**Comment by Joris000** [comment]
thanks a lot!! It's great
