### ISSUE TITLE
Banner - 3X

### ISSUE THREAD

**Issue by sirkisselgof** [popcorndao/Marketing-Ad-hoc#32]
3X Banner - FRA#891
We need a banner for a new product, 3X.

It has exposure to EURO stablecoins agEUR, EURt, and EURs, as well as USD stablecoins FRAX, alUSD, and FEI.

Slogan: EURO € exposure with noble yield that funds social impact organizations.

Please incorporate below banners into the banner. Perhaps you just need €, FRAX, alUSD, and FEI only.

3EUR Pool:
-agEUR
-EURt
-EURs
https://curve.fi/factory/66

D3 Pool:
-FRAX
-alUSD
-FEI
https://curve.fi/factory/57

**Comment by annisharafi** [comment]
updated @sirkisselgof 
![introducing 3X](https://user-images.githubusercontent.com/22950097/171901523-a52d3b16-d59c-412e-b09a-529104474ab3.png)

**Comment by sirkisselgof** [comment]
This looks great, but we need all 3 EUR tokens in there, preferably with agEUR, EURt, and EURs next to each other, and FRAX, FEI, and alUSD next to each other.

agEUR: https://github.com/AngleProtocol/angle-assets/tree/main/0_angle-tokens/agEUR

EURt: https://www.blockchaincenter.net/krypto-boersen/?crypto=EURT

**Comment by sirkisselgof** [comment]
Hi @annisharafi checking in here, thanks

**Comment by annisharafi** [comment]
updated @sirkisselgof
![introducing 3X](https://user-images.githubusercontent.com/22950097/172127071-62b6ecc7-dee6-482a-a562-f24d5837a8e5.png)

**Comment by FanFanDAO** [comment]
@sirkisselgof is this done?

**Comment by sirkisselgof** [comment]
EURS and alUSD logos are blurry. can you fix that?

The tokens names are also case sensitive. Please make sure they're spelled like the following:

agEUR EURT EURS FRAX FEI alUSD

**Comment by annisharafi** [comment]
updated @sirkisselgof 
![introducing 3X.png](https://images.zenhubusercontent.com/6138be30f402af74c178f38b/da2e72f9-8a60-4558-be25-3cdd8d852223)

**Comment by sirkisselgof** [comment]
thanks!

**Comment by sirkisselgof** [comment]
Sorry, one last edit. The copy should read:

"EUR & USD exposure with noble yield
that funds social impact organizations"

**Comment by sirkisselgof** [comment]
Sorry, have to redo this one more time given we're dropping FRAX, FEI, alUSD.

We need these logos as a replacement below:
DAI
USDC
USDT
sUSD

**Comment by FanFanDAO** [comment]
@sirkisselgof 
![introducing 3X.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/f31ecd23-054d-4353-a256-3f2e9ede8ec3)
