### ISSUE TITLE
Beneficiary Twitter Space with Gaia Gives and Carbon Lamina POP

### ISSUE THREAD

**Issue by Joris000** [popcorndao/Marketing-Ad-hoc#33]
**Description**
We need a banner with the logos of Popcorn, Gaia Gives and Lamina POP to promote our second beneficiary spaces on twitter next Tuesday. We would need this as soon as possible. 
**Specific Acceptance Criteria**
None
**Resources**
File links
Logo Gaia Gives: 
![Typeform  Gaia_Gives_Logo_Teal_1200](https://user-images.githubusercontent.com/106169378/173066441-57fba49b-a4ff-47d9-8101-2a79d267db10.png)
Logo Lamina POP: 
<img width="256" alt="Bildschirmfoto 2022-06-10 um 13 44 01" src="https://user-images.githubusercontent.com/106169378/173066794-bac26b81-ace6-4bb7-a3e4-38960eeb62fc.png">
**General Requirements**
Similar design than the last one:  
![FUBW6AJWAAUdqfq](https://user-images.githubusercontent.com/106169378/173065985-2a5d680e-236f-4903-856a-c1b4516e8316.jpeg)
* banner title : Popcorn Social Impact Spotlight 
* date & time : Tuesday, June 14th, 7pm CET
* speaker : 
    * Matt Gillespie, Head of Product at Gaia Gives  
    * Marcus Alburez Myers, COO at Lamina POP
**Image References**
Mail attachments

**Comment by annisharafi** [comment]
updated @Joris000 
![Popcorn Foundation Beneficiary Twitter Spaces Vol 2](https://user-images.githubusercontent.com/22950097/173106477-8cb9265b-1151-458d-b78c-2ffd830ff232.jpg)

**Comment by Joris000** [comment]
Thank you so much! @annisharafi
