### ISSUE TITLE
Soical Impact Spotlight with oneukraine

### ISSUE THREAD

**Issue by Joris000** [popcorndao/Marketing-Ad-hoc#37]
Description
We need a banner with the logos of Popcorn and oneukraine to promote our third beneficiary spaces on twitter tomorrow. We would need this as soon as possible.
**Specific Acceptance Criteria**
None
**Resources**
**File links**
Logo oneukraine:
<img width="124" alt="oneukraine_logo" src="https://user-images.githubusercontent.com/106169378/178276198-bdc0b748-069c-4da5-9bd2-358c056c4f58.png">

General Requirements
Similar design than the last one:  
![FUBW6AJWAAUdqfq](https://user-images.githubusercontent.com/106169378/178276318-471048ba-add9-4e9b-9cd2-92eb9d082b29.jpeg)

banner title : Popcorn Social Impact Spotlight
date & time : Tuesday, July 12th, 7pm CET
speaker : Vlad Bakaliar, role: Leadership Team at ONE UKRAINE

Image References
Mail attachments

**Comment by annisharafi** [comment]
updated
![Social Media_Social Impact Spotlight.jpg](https://images.zenhubusercontent.com/6138be30f402af74c178f38b/57362f59-048f-45d6-9543-6ecaf16a72fe)

**Comment by Joris000** [comment]
thank you!

**Comment by Joris000** [comment]
Hey @annisharafi, we had to move the twitter spaces could you update it with the following information: 
banner title : Popcorn Social Impact Spotlight
date & time : Thursday, July 14th, 7pm CET
speakers: 
Vlad Bakaliar, role: Leadership Team at ONE UKRAINE
Maxwell Fein, role: Founder of There is Life

This is the logo of There is Life:
![Final Logo](https://user-images.githubusercontent.com/106169378/178363332-cc7164cf-8553-4862-9bf6-c7cc650319a7.png)

**Comment by annisharafi** [comment]
@Joris000 updated
![Social Impact Spotlight](https://user-images.githubusercontent.com/22950097/178460476-07709cd2-f3d1-48e5-802b-82e016859ce6.jpg)

**Comment by Joris000** [comment]
Thank you!!
