### ISSUE TITLE
AMA graphics for Friday 5pm UTC

### ISSUE THREAD

**Issue by split-infinity** [popcorndao/Marketing-Ad-hoc#5]
Community AMA Friday 5pm UTC

Butter Hall on Discord

I believe we have an AMA template?

**Comment by FanFanDAO** [comment]
@split-infinity Which AMA? Internal? What is the specific dates and details?

**Comment by annisharafi** [comment]
Design update with two alternatives blue and orange

![AMA-Blue.jpg](https://images.zenhubusercontent.com/6138be30f402af74c178f38b/7babcb64-9902-456f-8a65-03ea599ff9f9)![AMA-Orange.jpg](https://images.zenhubusercontent.com/6138be30f402af74c178f38b/971a1c1c-ae0e-4600-a4fa-86d2f59f82ef)[Uploading... Blue.jpg]

**Comment by FanFanDAO** [comment]
Anna-Marie's name corrected.
![Blue.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/dd4b6a63-9015-452f-b833-6589c6630419)![orange.jpg](https://images.zenhubusercontent.com/61810500aff7360d9ccd5db3/90f2e78a-be83-41b7-a2c2-89fd2b1eade1)
